from graph import Graph

# Link para ver os vizinhos
# https://www.cidade-brasil.com.br/estado-sergipe.html?c=nom

def instance():
  graph_citys_sergipe = Graph()

  vertex_amparo_de_sao_francisco = Vertex("Amparo de São Francisco", 1)
  vertex_aquidaba = Vertex("Aquidabã", 2)
  vertex_aracaju = Vertex("Aracaju", 3)
  vertex_araua = Vertex("Arauá", 4)
  vertex_areia_branca = Vertex("Areia Branca", 5)
  vertex_barra_dos_coqueiros = Vertex("Barra dos Coqueiros", 6)
  vertex_boquim = Vertex("Boquim", 7)
  vertex_brejo_grande = Vertex("Brejo Grande", 8)
  vertex_campo_do_brito = Vertex("Campo do Brito", 9)
  vertex_canhoba = Vertex("Canhoba", 10)
  vertex_caninde_de_sao_francisco = Vertex("Canindé de São Francisco", 11)
  vertex_capela = Vertex("Capela", 12)
  vertex_carira = Vertex("Carira", 13)
  vertex_carmopolis = Vertex("Carmópolis", 14)
  vertex_cedro_de_sao_joao = Vertex("Cedro de São João", 15)
  vertex_cristinapolis = Vertex("Cristinápolis", 16)
  vertex_cumbe = Vertex("Cumbe", 17)
  vertex_divina_pastora = Vertex("Divina Pastora", 18)
  vertex_estancia = Vertex("Estância", 19)
  vertex_feira_nova = Vertex("Feira Nova", 20)
  vertex_frei_paulo = Vertex("Frei Paulo", 21)
  vertex_gararu = Vertex("Gararu", 22)
  vertex_general_maynard = Vertex("General Maynard", 23)
  vertex_gracho_cardoso = Vertex("Gracho Cardoso", 24)
  vertex_ilha_das_flores = Vertex("Ilha das Flores", 25)
  vertex_indiaroba = Vertex("Indiaroba", 26)
  vertex_itabaiana = Vertex("Itabaiana", 27)
  vertex_itabaianinha = Vertex("Itabaianinha", 28)
  vertex_itabi = Vertex("Itabi", 29)
  vertex_itaporanga_d_ajuda = Vertex("Itaporanga d’Ajuda", 30)
  vertex_japaratuba = Vertex("Japaratuba", 31)
  vertex_japoata = Vertex("Japoatã", 32)
  vertex_lagarto = Vertex("Lagarto", 33)
  vertex_laranjeiras = Vertex("Laranjeiras", 34)
  vertex_macambira = Vertex("Macambira", 35)
  vertex_malhada_dos_bois = Vertex("Malhada dos Bois", 36)
  vertex_malhador = Vertex("Malhador", 37)
  vertex_maruim = Vertex("Maruim", 38)
  vertex_moita_bonita = Vertex("Moita Bonita", 39)
  vertex_monte_alegre_de_sergipe = Vertex("Monte Alegre de Sergipe", 40)
  vertex_muribeca = Vertex("Muribeca", 41)
  vertex_neopolis = Vertex("Neópolis", 42)
  vertex_nossa_senhora_aparecida = Vertex("Nossa Senhora Aparecida", 43)
  vertex_nossa_senhora_da_gloria = Vertex("Nossa Senhora da Glória", 44)
  vertex_nossa_senhora_das_dores = Vertex("Nossa Senhora das Dores", 45)
  vertex_nossa_senhora_de_lourdes = Vertex("Nossa Senhora de Lourdes", 46)
  vertex_nossa_senhora_do_socorro = Vertex("Nossa Senhora do Socorro", 47)
  vertex_pacatuba = Vertex("Pacatuba", 48)
  vertex_pedra_mole = Vertex("Pedra Mole", 49)
  vertex_pedrinhas = Vertex("Pedrinhas", 50)
  vertex_pinhao = Vertex("Pinhão", 51)
  vertex_pirambu = Vertex("Pirambu", 52)
  vertex_porto_da_folha = Vertex("Porto da Folha", 53)
  vertex_poco_redondo = Vertex("Poço Redondo", 54)
  vertex_poco_verde = Vertex("Poço Verde", 55)
  vertex_propria = Vertex("Propriá", 56)
  vertex_riachuelo = Vertex("Riachuelo", 57)
  vertex_riachao_do_dantas = Vertex("Riachão do Dantas", 58)
  vertex_ribeiropolis = Vertex("Ribeirópolis", 59)
  vertex_rosario_do_catete = Vertex("Rosário do Catete", 60)
  vertex_salgado = Vertex("Salgado", 61)
  vertex_santa_luzia_do_itanhy = Vertex("Santa Luzia do Itanhy", 62)
  vertex_santa_rosa_de_lima = Vertex("Santa Rosa de Lima", 63)
  vertex_santana_do_sao_francisco = Vertex("Santana do São Francisco", 64)
  vertex_santo_amaro_das_brotas = Vertex("Santo Amaro das Brotas", 65)
  vertex_simao_dias = Vertex("Simão Dias", 66)
  vertex_siriri = Vertex("Siriri", 67)
  vertex_sao_cristovao = Vertex("São Cristóvão", 68)
  vertex_sao_domingos = Vertex("São Domingos", 69)
  vertex_sao_francisco = Vertex("São Francisco", 70)
  vertex_sao_miguel_do_aleixo = Vertex("São Miguel do Aleixo", 71)
  vertex_telha = Vertex("Telha", 72)
  vertex_tobias_barreto = Vertex("Tobias Barreto", 73)
  vertex_tomar_do_geru = Vertex("Tomar do Geru", 74)
  vertex_umbauba = Vertex("Umbaúba", 75)
  
  #vizinhos_amparo
  
  edge_amparo_telha = Edge(vertex_amparo_de_sao_francisco, vertex_telha, 6.2)
  edge_amparo_canhoba = Edge(vertex_amparo_de_sao_francisco, vertex_canhoba, 6.6)
  edge_amparo_cedro = Edge(vertex_amparo_de_sao_francisco, vertex_cedro_de_sao_joao, 11.1)
  edge_amparo_propria = Edge(vertex_amparo_de_sao_francisco, vertex_propria, 12.6)
  edge_amparo_aquidaba = Edge(vertex_amparo_de_sao_francisco, vertex_aquidaba, 16)
  edge_amparo_itabi = Edge(vertex_amparo_de_sao_francisco, vertex_itabi, 19.4)
  edge_amparo_sao_francisco = Edge(vertex_amparo_de_sao_francisco, vertex_sao_francisco, 19.7)
  edge_amparo_malhada_dos_bois = Edge(vertex_amparo_de_sao_francisco, vertex_malhada_dos_bois, 20.3)
  edge_amparo_japoata = Edge(vertex_amparo_de_sao_francisco, vertex_japoata, 24.1)
  edge_amparo_gararu = Edge(vertex_amparo_de_sao_francisco, vertex_gararu, 27.9)
  edge_amparo_muribeca = Edge(vertex_amparo_de_sao_francisco, vertex_muribeca, 29.3)
  edge_amparo_graccho = Edge(vertex_amparo_de_sao_francisco, vertex_gracho_cardoso, 30.1)
  edge_amparo_cumbe = Edge(vertex_amparo_de_sao_francisco, vertex_cumbe, 34.4)
  edge_amparo_santana_do_s_f = Edge(vertex_amparo_de_sao_francisco, vertex_santana_do_sao_francisco, 39.9)
  edge_amparo_capela = Edge(vertex_amparo_de_sao_francisco, vertex_capela, 40.5)
  
  graph.add_edge(edge_amparo_telha)
  graph.add_edge(edge_amparo_canhoba)
  graph.add_edge(edge_amparo_cedro)
  graph.add_edge(edge_amparo_propria)
  graph.add_edge(edge_amparo_aquidaba)
  graph.add_edge(edge_amparo_itabi)
  graph.add_edge(edge_amparo_sao_francisco)
  graph.add_edge(edge_amparo_malhada_dos_bois)
  graph.add_edge(edge_amparo_japoata)
  graph.add_edge(edge_amparo_gararu)
  graph.add_edge(edge_amparo_muribeca)
  graph.add_edge(edge_amparo_graccho)
  graph.add_edge(edge_amparo_cumbe)
  graph.add_edge(edge_amparo_santana_do_s_f)
  graph.add_edge(edge_amparo_capela)
  
  #vizinhos_aquidaba
  
  edge_aquidaba_malhada_dos_bois = Edge(vertex_aquidaba, vertex_malhada_dos_bois, 12.9)
  edge_aquidaba_cedro = Edge(vertex_aquidaba, vertex_cedro_de_sao_joao, 15.4)
  edge_aquidaba_sao_francisco = Edge(vertex_aquidaba, vertex_sao_francisco, 15.8)
  edge_aquidaba_canhoba = Edge(vertex_aquidaba, vertex_canhoba, 16.6)
  edge_aquidaba_telha = Edge(vertex_aquidaba, vertex_telha, 17.2)
  edge_aquidaba_muribeca = Edge(vertex_aquidaba, vertex_muribeca, 17.3)
  edge_aquidaba_cumbe = Edge(vertex_aquidaba, vertex_cumbe, 20)
  edge_aquidaba_itabi = Edge(vertex_aquidaba, vertex_itabi, 20.4)
  edge_aquidaba_propria = Edge(vertex_aquidaba, vertex_propria, 20.6)
  edge_aquidaba_graccho = Edge(vertex_aquidaba, vertex_gracho_cardoso, 20.9)
  edge_aquidaba_japoata = Edge(vertex_aquidaba, vertex_japoata, 24.7)
  edge_aquidaba_capela = Edge(vertex_aquidaba, vertex_capela, 25.6)
  edge_aquidaba_dores = Edge(vertex_aquidaba, vertex_nossa_senhora_das_dores, 30.3)
  edge_aquidaba_feira_nova = Edge(vertex_aquidaba, vertex_feira_nova, 31.9)
  edge_aquidaba_japaratuba = Edge(vertex_aquidaba, vertex_japaratuba, 35.9)
  edge_aquidaba_gararu = Edge(vertex_aquidaba, vertex_gararu, 35.9)
  
  graph.add_edge(edge_aquidaba_malhada_dos_bois)
  graph.add_edge(edge_aquidaba_cedro)
  graph.add_edge(edge_aquidaba_sao_francisco)
  graph.add_edge(edge_aquidaba_canhoba)
  graph.add_edge(edge_aquidaba_telha)
  graph.add_edge(edge_aquidaba_muribeca)
  graph.add_edge(edge_aquidaba_cumbe)
  graph.add_edge(edge_aquidaba_itabi)
  graph.add_edge(edge_aquidaba_propria)
  graph.add_edge(edge_aquidaba_graccho)
  graph.add_edge(edge_aquidaba_japoata)
  graph.add_edge(edge_aquidaba_capela)
  graph.add_edge(edge_aquidaba_dores)
  graph.add_edge(edge_aquidaba_feira_nova)
  graph.add_edge(edge_aquidaba_japaratuba)
  graph.add_edge(edge_aquidaba_gararu)